name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      RUST_VERSION: 1.53
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: build
        uses: ashutoshvarma/action-cmake-build@master
      - name: check visuals
        run: cd visual && cargo check
